### PR TITLE
Ft 163696381 fetch incident records data

### PR DESCRIPTION
**Pull request by Rhytah**
## What does this PR do?
-  User has the ability to retrieve different incident data records respective of their needs by entering the `incident_id` in search option. Result should be data corresponding to that particular `incident_id`

## Tasks.
- [x] Refactor html code.
- [x] Write scripts that fetch data and make it readable to the user.
- [x] Verify the data returned versus the data presented.

## How should this be manually test?
[gh-pages](https://rhytah.github.io/iReporter-integrated/UI/forum.htm)
You should login first in order to manipulate data. 

## Relevant pivotal tracker stories.
#163850042

## Reviewers
@kalsmic @nicholusmuwonge @mwinel @richien @llwasampijja

### Known bugs:
- application not fully responsive

### CODE REVIEW

**Comment by ghost** [comment]
@Rhytah, I took time and viewed your UI but:-
- I was logged in automatically.
however, according to the PR, I tried the functionality of picking the incident by id. and it worked well.

**Comment by kalsmic** [comment]
@Rhytah, In addition to @ManuelDominic's comment. I would rather you made the search for specific red-flag to be by say the title or the comment, something the user can easily relate with.

**Comment by Rhytah** [comment]
> 
> 
> @Rhytah, I took time and viewed your UI but:-
> 
>     * I was logged in automatically.
>       however, according to the PR, I tried the functionality of picking the incident by id. and it worked well.

Thank you for pointing this out, let me get to fixing it ASAP.

**Comment by mwinel** [comment]
I have tried to fetch a single intervention by ID but it is not returning any values...
This app automatically logs me in when I try to [access this page.](https://rhytah.github.io/iReporter-integrated/UI/forum.htm)

**Pull request merged**
